### PR TITLE
Improve styling of admin/login page

### PR DESCRIPTION
**Pull request by jasonlbeggs**
I updated the styling of the admin login page. I am working on updating the rest of the admin area.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you for this, I'll leave this PR open so you can add commits for the admin area! 👍

**Comment by jasonlbeggs** [comment]
Thanks! I upgrade Tailwind to the most recent version. I'm pretty sure it didn't break anything, but you might want to give it a quick look just to make sure.

**Comment by freekmurze** [comment]
I'll be sure to check your changes locally before pushing to production.

**Comment by jasonlbeggs** [comment]
There was one problem. I forgot to fix the Tailwind default config function call. It will be corrected in my next commit.

**Comment by freekmurze** [comment]
Np, let me know you're done with styling the admin, and I'll have a look.

**Comment by jasonlbeggs** [comment]
I finished the Posts page and navigation. Let me know if you like the style and I will work on the other pages a little later.

**Comment by freekmurze** [comment]
Looks really great already! Nice job!

**Pull request merged**
