### PR TITLE
Improve resonsiveness/styling of newsletter partial

### PR DESCRIPTION
**Pull request by jasonlbeggs**
Changes made to the classes of the newsletter partial to make the design more consistent with the search field. Also made changes to margin and borders at certain break-points. Added a break-point to help with consistency.

Examples at various break-points from before and after: 
preview

Let me know if anything needs to be changed or you would like similar changes made to other sections of the site. I'd be happy to help out!

### CODE REVIEW

**Comment by jasonlbeggs** [comment]
I also made similar changes to the main newsletter signup form on the newsletter page. All the inputs and buttons and consistent styling now.

**Comment by freekmurze** [comment]
Thank you very much!

**Comment by freekmurze** [comment]
> Let me know if anything needs to be changed or you would like similar changes made to other sections of the site. I'd be happy to help out!

If you have some time on your hands, I'd appreciate PRs that clean up the layout of the `/admin` section. If haven't got around to that myself yet (it's really messy now). Goes without saying that you really don't have to feel yourself obligated to do this. Only do it if you want to play around with Tailwind a bit more.

**Comment by jasonlbeggs** [comment]
I'd be happy to. I will work on it in the next few days and see what I can do! Thanks!

**Comment by freekmurze** [comment]
Awesome, thanks!

**Pull request merged**
